POST http://localhost:8080/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8080/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json/Rating

###

GET http://localhost:8081/ratings/getAll
Content-Type: application/json

###

POST https://localhost:8081/ratings/editRatings
Content-Type application/json
{
    {
        "_id":"643f17b1a241318be6043ec7",
        "username":"Nand Patel",
        "stationName":"Government Center",
        "ratings":2,
        "comments":"Sprint 4 in progress!!!",
        "date":"2023-04-18T22:20:33.905Z","__v":0
    }
}


###

POST http://localhost:8081/ratings/add
Content-Type application/json

###
###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
POST  http://localhost:8081/user/deleteAll
